version: '3.8'

services:
  box-office-api:
    build: .
    container_name: box-office-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/box_office.db
      - LOG_LEVEL=INFO
      - DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s